### ISSUE TITLE
Using FindSeries with "The Strain" returns null

### ISSUE THREAD

**Issue by glitch452** [WilliamABradley/TVMazeSharp#1]
Firstly, great Job on this API!  

I integrated it into my project, and it works well except for a problem I found when searching for some shows using TVMaze.FindSeries().  

When searching for "The Strain", the returned result is null.  This is odd considering that when searching for "This is not a show" a collection (IReadOnlyCollection) with 0 elements is returned.  

Example (Throws exception "object reference nor set to an instance of an object"):
IReadOnlyCollection<SearchContainerShow> mazeSeriesList = await TVMaze.FindSeries("The Strain");
if (mazeSeriesList.Count == 0) {  } 

When I try searching for the strain with TVMaze.FindSingleSeries("The Strain"), it returns the MazeSeries properly.  

I was wondering if this might help you solve a bug or if there is something I am doing wrong?

**Comment by glitch452** [comment]
I found the source of the problem.  

When searching for "The Strain", one of the possible results has a blank premiered date.  This is causing JSON Parse error: "Error converting value {null} to type 'System.DateTime'. Path '[2].show.premiered', line 1, position 2479."

Perhaps the API could be updated to handle this type of failure gracefully?

Another thing to look at.. When calling the _Get method, it tries to return the _404Stub if there is a bad response from the HttpClient.  This would be OK when searching for a MazeSeries, but would it not have a problem when using _Get with the collection of SearchContainerShow? (IReadOnlyCollection<SearchContainerShow>)

**Comment by PhyxionNL** [comment]
This is happening for a lot of data, I changed nearly all properties to <type>? <name> to also allow null values.

**Comment by WilliamABradley** [comment]
This has been fixed in the latest release with nullable datetime classes.
